# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.1
    hooks:
        # Run the linter.
    -   id: ruff
        args: [ --fix ]
        # Run the formatter.
    -   id: ruff-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^site/
    -   id: end-of-file-fixer
        exclude: ^site/
    -   id: check-yaml
        exclude: ^site/|^conf/deployment.yml
    -   id: check-added-large-files
        exclude: ^site/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
        args: [--strict, --ignore-missing-imports]
        exclude: ^tests/|^notebooks/
-   repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
    -   id: pip-compile
        name: pip-compile pyproject.toml
        files: ^pyproject.toml$
        args: [pyproject.toml, --extra=dev, --output-file=requirements_dev.txt, --annotation-style=line, --no-emit-trusted-host, --no-emit-index-url, --allow-unsafe, --resolver=backtracking]
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--exclude-files', '.*\.ipynb$', ]
        files: ^notebooks/|^ae_utils/|requirements_dev.txt|requirements.txt
