name: test_and_deploy_docu

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocstrings[python] mike
      - run: |
          if [ ${{ github.ref }} == "refs/heads/main" ]; then
            mkdocs gh-deploy --force
          else
            mkdocs build --strict
          fi
        shell: bash
