name: check_version_update
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Check Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Changelog check
        uses: Zomzog/changelog-checker@v1.2.0
        with:
          fileName: VERSION # default `CHANGELOG.adoc`
          noChangelogLabel: version not updated # default `no changelog`
          checkNotification: Simple # default `Detailed`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
